// national data actions
export const GET_NATIONAL_DATA_REQUEST = "GET_NATIONAL_DATA_REQUEST";
export const GET_NATIONAL_DATA_SUCCESS = "GET_NATIONAL_DATA_SUCCESS";
export const GET_NATIONAL_DATA_FAILED = "GET_NATIONAL_DATA_FAILED";
export const SET_NATIONAL_SORTING = "SET_NATIONAL_SORTING";
export const SET_GRAPH_INPUT = "SET_GRAPH_INPUT";

// regional data actions
export const GET_REGIONAL_DATA_REQUEST = "GET_REGIONAL_DATA_REQUEST";
export const GET_REGIONAL_DATA_SUCCESS = "GET_REGIONAL_DATA_SUCCESS";
export const GET_REGIONAL_DATA_FAILED = "GET_REGIONAL_DATA_FAILED";
export const SET_REGIONAL_SORTING = "SET_REGIONAL_SORTING";
export const SET_REGIONAL_FILTER = "SET_REGIONAL_FILTER";

// provincial data actions
export const GET_PROVINCIAL_DATA_REQUEST = "GET_PROVINCIAL_DATA_REQUEST";
export const GET_PROVINCIAL_DATA_SUCCESS = "GET_PROVINCIAL_DATA_SUCCESS";
export const GET_PROVINCIAL_DATA_FAILED = "GET_PROVINCIAL_DATA_FAILED";
export const SET_PROVINCIAL_SORTING = "SET_PROVINCIAL_SORTING";
export const SET_PROVINCIAL_FILTER = "SET_PROVINCIAL_FILTER";
export const SET_PROVINCIAL_FILTER_REGION = "SET_PROVINCIAL_FILTER_REGION";
export const SET_HISTORICAL_PROVINCIAL_FILTER =
  "SET_HISTORICAL_PROVINCIAL_FILTER";
